### PR TITLE
detailed/extended error messages

### PR DESCRIPTION
**Pull request by HonoluluHenk**
return constraint args in ValidationError in a backwards compatible way.

Might help a lot with: 
- How to make it multi language #230
- How to customize validation messages globally? #169

### CODE REVIEW

**Comment by jrjohnson** [comment]
Would be interested to know why this is lingering with no review. It seems to be a big part of what is needed to translate error messages without having to re-implement each validator. If it's a bad approach could you suggest something better and I'll take a shot at a pull request?

**Comment by NoNameProvided** [comment]
Hi! 

Sorry for the late review. Can you rebase this to the current develop (or create a new PR). You will have to
 - update your tests as we moved to Jest from Mocha
 - replace the class definition with an interface, adding it into `src/interfaces`

**Comment by candunaj** [comment]
Hi, 
I am looking forward to see this commit merged. I am refreshing every hour if it was merged. I can use this class-validator only if I am able to make custom messages.

Thank you

**Comment by glen-84** [comment]
@HonoluluHenk Will you continue working on this PR?

**Comment by jannomeister** [comment]
is this still going to be reviewed?

**Comment by HonoluluHenk** [comment]
Unfortunately, I cannot invest anymore time into this PR :(

**Comment by NoNameProvided** [comment]
Closing this as the author noted he is not interested in pushing this anymore.  

If someone wants to pick this up, please open a feature idea first on the discussion tab to decide how we want to approach this.

**Pull request closed without merging**
