### PR TITLE
Add example for .validateOrReject usage

### PR DESCRIPTION
**Pull request by vvscode**

### CODE REVIEW

**Comment by vvscode** [comment]
And in general - I see no documentation for `Validator` class. My example is described in tests https://github.com/typestack/class-validator/pull/44/files#diff-27b51e6f3099f1a9738d41affcf20acdR36 but it will be nice to see it in docs

**Comment by vvscode** [comment]
@amirsaber  any ideas about why the test failed?

**Comment by vlapo** [comment]
Why not use only `validateOrReject()` function? We should prefer one way in documentation.

Tests failed because of gulp. Fixed in latest source. Please rebase.

**Comment by vlapo** [comment]
Also we have existing PR about validateOrReject https://github.com/typestack/class-validator/pull/320/files

**Comment by vvscode** [comment]
@vlapo  I just didn't find a `valideOrReject()` in docs, and this one is first I discovered according tests

**Comment by vlapo** [comment]
@vvscode thnx for PR but I think we should accept https://github.com/typestack/class-validator/pull/320. It also update `docs/basics/validating-objects.md` and I think we should use `validateOrReject` root function as preferred in docs.

**Pull request closed without merging**
