### PR TITLE
feat: add decorator name to validation metadata

### LINKED ISSUE #622: The names of the decorators are lost in the MetadataStorage
### Description

Since the 0.12.x update, the names of the decorators are lost when stored.
For example, when the `IsString` decorator is used, the metadata store a new entry with the type `customValidation` instead of `isString`. This seems to apply to all decorators, because of this line: https://github.com/typestack/class-validator/blob/1955250de64d76504df465aa02076a2e5b219bb7/src/register-decorator.ts#L80.

### Reproduction

Inspect the stored metadata with `getMetadataStorage().getTargetValidationMetadatas` and you'll see that all entries' `type`s are `customValidation`, instead of their decorator names.

### Environment

- [ ] nodejs: 10.18.1
- [ ] browser: no
- [ ] framework/library: standalone

**class-validator version:** <code>0.12.2</code>

### PR DESCRIPTION
**Pull request by Clashsoft**
## Description
Added the optional `name` property to `ValidationMetadata` which is set from `options` in `registerDecorator`.
Previously, the information in `options.name` was lost - it was not possible to find out which concrete decorators are present in a class.

See #622.

## Checklist
- [x] the pull request title describes what this PR does (not a vague title like `Update index.md`)
- [x] the pull request targets the *default* branch of the repository (`develop`)
- [x] the code follows the established code style of the repository
  - `npm run prettier:check` passes
  - `npm run lint:check` passes
- [ ] tests are added for the changes I made (if any source code was modified)
    > not applicable, there is no new logic, only additional data being passed
- [x] documentation added or updated
    > I added jsdoc comments.
    > Otherwise not applicable, the affected part of the code is not documented for end users
- [x] I have run the project locally and verified that there are no errors

### Fixes
references #622

### CODE REVIEW

**Review by Prim3591 — DISMISSED** [review]

**Comment by Clashsoft** [comment]
@Prim3591 thanks for approving, can you approve the workflow run as well please?

**Comment by Clashsoft** [comment]
@Prim3591 Bumping this, I still have an ongoing project that is blocked by this change...

**Comment by Prim3591** [comment]
> @Prim3591 Bumping this, I still have an ongoing project that is blocked by this change...

Thank you for your enthusiasm but I'm not an admin on this repo, and thus not able to merge it. I've just reviewed it because I need it too, by doing so I was expecting the "real admin" could perform this task quicker :)

**Comment by NoNameProvided** [comment]
Can you rebase this please to the latest `develop`? (Instead of rebasing it's easier to cherry-pick it probably.)

**Comment by Clashsoft** [comment]
> Can you rebase this please to the latest `develop`? (Instead of rebasing it's easier to cherry-pick it probably.)

Done!

**Review by NoNameProvided — APPROVED** [review]

**Pull request merged**
