### PR TITLE
Remove google-libphonenumber and migrate to jest/eslint

### PR DESCRIPTION
**Pull request by rmuchall**
Hi there,

Following my PR to routing-controllers (https://github.com/typestack/routing-controllers/pull/553) I'm now submitting a similar PR for class-validator.

**Action taken**
Removed google-libphonenumber
**Reasoning**
google-libphonenumber is huge. Although a work-around exists I believe the better option is to remove it. See (https://github.com/typestack/class-validator/issues/248)

**Action taken**
Replaced mocha, chai, sinon and nyc with jest
**Reasoning**
To normalize the test framework across all my projects
Jest appears to be a more complete framework
Jest is more popular
https://npmcompare.com/compare/jest,mocha

**Action taken**
Replaced gulp with npm scripts (copyfiles, json, rimraf)
**Reasoning**
Gulp is awesome but we can achieve the same result by using npm scripts (same as routing-controllers)

**Action taken**
Replaced tslint with eslint
**Reasoning**
tslint is deprecated and the recommended replacement is eslint

**Other changes**
Updated all dependencies

Thanks,
Rob

### CODE REVIEW

**Comment by vlapo** [comment]
Hi @rmuchall. Thank you for creating this PR! Unfortunately we have one big PR in review (https://github.com/typestack/class-validator/pull/568) and we have to wait until merge. But after merging I am open check this PR. For now just few comments from my side:
 - remove google-libphonenumber - https://github.com/typestack/class-validator/pull/568 introduce tree shaking so I would not remove this validator
 - **use jest to testing - sure I love it!**
 - remove gulp - https://github.com/typestack/class-validator/pull/568 change build and packaging process to more complex one. I think we should keep all "scripts" on one place and it is gulpfile for now -  but I am open to change this in future
 - **eslint - sure love it!**

**Comment by rmuchall** [comment]
Hi @vlapo,
Many thanks for your feedback.
I'm happy to modify my PR to meet your requirements.
Thank you for all your hard work on this library! :)

**Comment by vlapo** [comment]
Hi @rmuchall.
https://github.com/typestack/class-validator/pull/568 merged and I would love to see eslint and jest in our code. Could you please create two separate PRs? One for jest and one for eslint.

**Comment by rmuchall** [comment]
Hi @vlapo 
No problem. I will close this PR and open 2 new ones.

**Pull request closed without merging**
