### PR TITLE
feat: added IsIPRange validator

### PR DESCRIPTION
**Pull request by notmedia**
## Description
Added IsIPRange validator

Also, the problem was in typings. I just created PR to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53666 with fixes. After this PR will be merged, I'll update type deps here and we can merge.

## Checklist

- [x] the pull request title describes what this PR does (not a vague title like `Update index.md`)
- [x] the pull request targets the *default* branch of the repository (`develop`)
- [x] the code follows the established code style of the repository
  - `npm run prettier:check` passes
  - `npm run lint:check` passes
- [x] tests are added for the changes I made (if any source code was modified)
- [x] documentation added or updated
- [x] I have run the project locally and verified that there are no errors

### CODE REVIEW

**Comment by notmedia** [comment]
Done,  DefinitelyTyped/DefinitelyTyped#53666 was merged.

**Comment by notmedia** [comment]
@NoNameProvided Hi! Can you review this PR please?

**Comment by braaar** [comment]
Hi, @notmedia, could you rebase/merge this PR and get rid of the irrelevant changes to package.json and such?

**Comment by NoNameProvided** [comment]
Closing this as expired, no response from PR author.

**Pull request closed without merging**
