### PR TITLE
refactor: use unknown type for validation functions inputs

### PR DESCRIPTION
**Pull request by henrikra**
I have refactored all `value` parameters correctly to `unknown` type. In short `unknown` type is like `any` but more strict because it forces you to make validation to it.

Before this PR lot of `value` looked like they have unneeded validation. For example:

```ts
isAscii(value: string): boolean {
  return typeof value === "string" && this.validatorJs.isAscii(value);
}
```

In this case it looks odd that why we have to validate that `value` is a string since we are telling TS that it is already a string. Correct way of doing this is like here: 

```ts
isAscii(value: unknown): boolean {
  return typeof value === "string" && this.validatorJs.isAscii(value);
}
```

This is correct since we cannot pass `value` to `this.validatorJs.isAscii` before we validate that the `value` is string 👍 

The side effect of this changes is that I might have caught some bugs. For example in `isNumber` we never checked that the `value` is number since you cannot pass anything you want to `Number.isNaN`. But we are checking that and are sure that everything works as expected :)

More info about `unknown` type here https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#new-unknown-top-type

### CODE REVIEW

**Comment by henrikra** [comment]
@vlapo Do you have time to check this out? Tell me if you need some more info :)

**Comment by vlapo** [comment]
Firstly I have to check this (for me) new `unknown` type. Dont worry I have this on my list. 
But we have more important tasks to done. Check new milestone https://github.com/typestack/class-validator/milestone/3 if you want more contribute :)

**Comment by henrikra** [comment]
Hmm okay. Would it make sense to make new release always when new fix or feature is in master? Because if you want all of those in 0.10.1 it takes a lot of time and has many reasons for it to break instead of releasing in small increments :)

**Comment by vlapo** [comment]
Version name `0.10.1` is only orientational. We can release 0.10.1 with fixes before all issues are resolved. I just want to pick some issues and make a list. But feel free to suggest issues to be included in the next release. I am open to all suggestions, contributions and helps.

**Comment by henrikra** [comment]
Hmm well lets see: for example this issue https://github.com/typestack/class-validator/issues/266 is not a fix it is a new feature which didn't exist before so I would fix that and then make new release and the new version should be 0.11.0 (https://semver.org/) because we have added new functionality NOT fixed :)

After that I would keep going like this that make fix/feature -> release -> repeat. This way it is easy to see why something breaks IF something breaks :)

**Comment by vlapo** [comment]
Sure I understand but we are still in `0.x` phase of versioning right now. I want to reserve increment of minor version number for cases when we have to break API (e.g. in our case updating validator.js library is almost every time breaking change). Hope we will reach `1.0` milestone soon and after that use semantic versioning.

To #266 - I think this is bug since `validator.js` implement this argument from beginning and `class-validator` not. But I agree it could be also adding new argument and support new feature/enhancement.

**Comment by henrikra** [comment]
@vlapo Have you considered this pr? :D

**Comment by henrikra** [comment]
@vlapo I really think this PR would help the code base a lot but what do you think should I close it someone else can do it later or should we review this? :D

**Comment by vlapo** [comment]
Hey @henrikra sorry for such a delay. This change looks reasonable to me too. I hope we will also enable `strict` flag for TS soon.
Lets merge it and we will see. Could you please rebase and update also new validators?

**Comment by henrikra** [comment]
@vlapo Now I have merged master and also added unknown to new functions!

And yeah you guys should definitely should concentrate on getting strict flag on 👍

**Comment by vlapo** [comment]
Thank you for your effort!

**Pull request merged**
