### PR TITLE
fix: apply custom constraint class validation to each item in the array

### PR DESCRIPTION
**Pull request by zd333**
When `@Validate` + some custom constraint class is used with `{ each: true }`, then it is expected to be applied to each item of the target object field:
https://github.com/typestack/class-validator/issues/260

### CODE REVIEW

**Comment by zd333** [comment]
@pleerock Hi! Please review.

**Comment by zd333** [comment]
@pleerock @NoNameProvided  please find a minute to review this.
If there is something I can improve/change before review (to make it easier) - please let me know.
Thank you.

**Comment by zd333** [comment]
@pleerock @NoNameProvided 
Hello.
Kindly reminding to review :)

**Comment by TrejGun** [comment]
works like magic, please merge

**Comment by TrejGun** [comment]
@vlapo ping!

**Comment by zd333** [comment]
@pleerock @NoNameProvided @vlapo this PR is waiting for review for several month and now has some conflicts wiith current code. I'm ready to resolve those, but not sure if it makes sense and somebody is going to review it.
If so - then please let me know and will update the code to resolve conflicts.
Thank you!

**Comment by Wissam-Sandbox** [comment]
@NoNameProvided Please take a look at @zd333's PR. It would help solve this issue.
Thanks!

**Comment by vlapo** [comment]
Hey @zd333, sorry for such delay. Could you please rebase and I will review PR. Thank you for your patient.

**Comment by zd333** [comment]
@vlapo rebased.
I believe now PR is ready for review, please take a look when you have time.
Thank you.

**Comment by vlapo** [comment]
Looks good. Tests are green, code looks really good. Again, thank you for your endurance.

**Pull request merged**
