### PR TITLE
feat(IsDecimal): implement 'IsDecimal' from validatorjs

### PR DESCRIPTION
**Pull request by nikvaessen**

### CODE REVIEW

**Comment by nikvaessen** [comment]
Not sure why the checks fail, `npm run test` passed locally :(

**Comment by vlapo** [comment]
Could you please rebase? Test environment should be fixed in latest branch.

**Comment by nikvaessen** [comment]
> Could you please rebase? Test environment should be fixed in latest branch.

There you go :)

**Comment by vlapo** [comment]
Thank you for contribute :)

**Pull request merged**
