### PR TITLE
feat: add option to set validation schema in nested validator

### PR DESCRIPTION
**Pull request by zender**
references #203

### CODE REVIEW

**Comment by NoNameProvided** [comment]
I am not sure on this API. We should pass it as a constraint and modify the ValidateNested decorator to expect a class definition as the first parameter.

**Comment by enrico-calzavara** [comment]
@NoNameProvided do you mean pass the nested schema name in the constraints array of the validation schema? And what about the class definition?

**Comment by diosney** [comment]
@NoNameProvided Any updates on this? Please, this is a showstopper for me to using the library, since I do use Interfaces instead of classes, so the use of the decorators is not a fix for me.

**Comment by 19majkel94** [comment]
@diosney 
pure `abstract class` is effectively an `interface`, so you can use it with decorators and other interfaces might implement an abstract class

**Comment by diosney** [comment]
@19majkel94 Thanks for the tip! I will check if it is possible for me to change from interface based type checking to abstract class based validation.

Thanks!

**Comment by NoNameProvided** [comment]
Closing this as this won't get merged in its current state. The issue stays open for discussion.

**Pull request closed without merging**
