### PR TITLE
Fix: Update isPostalCode locale codes note

### LINKED ISSUE #1043: fix: Missing some locale codes in note
### Description

ispostalcode can validate postcodes more countries than stated in the notes. By example; note is missing the country codes SG, SI, SK.

**Minimal code-snippet showcasing the problem**
 

```ts
/**
 * Check if the string is a postal code,
 * (locale is one of [ 'AD', 'AT', 'AU', 'AZ', 'BE', 'BG', 'BR', 'CA', 'CH', 'CZ', 'DE', 'DK', 'DO', 'DZ', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'ID', 'IE' 'IL', 'IN', 'IR', 'IS', 'IT', 'JP', 'KE', 'KR', 'LI', 'LT', 'LU', 'LV', 'MX', 'MT', 'MY', 'NL', 'NO', 'NP', 'NZ', 'PL', 'PR', 'PT', 'RO', 'RU', 'SA', 'SE', 'SG', 'SI', 'SK', 'TN', 'TW', 'UA', 'US', 'ZA', 'ZM' ] OR 'any'. If 'any' is used, function will check if any of the locals match. Locale list is validator.isPostalCodeLocales.).
 * If given value is not a string, then it returns false.
 */
```

### PR DESCRIPTION
**Pull request by StefSmit12**
## Description

Updated the locale codes note of isPostalCode, because not every possible locale code was in the notes.

## Checklist

- [x] the pull request title describes what this PR does (not a vague title like `Update index.md`)
- [x] the pull request targets the *default* branch of the repository (`develop`)
- [x] the code follows the established code style of the repository
  - `npm run prettier:check` passes
  - `npm run lint:check` passes
- [x] tests are added for the changes I made (if any source code was modified)
- [x] documentation added or updated
- [x] I have run the project locally and verified that there are no errors

### Fixes

fixes #1043

### CODE REVIEW

**Comment by braaar** [comment]
Could you rebase/merge this PR to get rid of irrelevant changes and double check that the docstring is still up to date?

**Comment by braaar** [comment]
@StefSmit12 could you rebase/merge and get rid of the irrelevant changes in this PR?

**Comment by braaar** [comment]
Hi @StefSmit12, could you rebase/merge this to get rid of irrelevant changes?

**Comment by NoNameProvided** [comment]
Thanks, I actually went the other way and removed the hard-coded JSDoc list. The function is typed so users will always see the up-to-date list of options as code completion. 

Landed in https://github.com/typestack/class-validator/commit/cf8d2c0602faef82d8964a8a6718242a945dd8db.

**Pull request closed without merging**
