### PR TITLE
fix: add default message for isPort validator

### PR DESCRIPTION
**Pull request by l2ubin**
isPort which was used to check whether a given number was actaully a port was missing the default message thrown in case of falsy values.

### CODE REVIEW

**Comment by vlapo** [comment]
Thank you :)

**Comment by l2ubin** [comment]
I would like to help out with other pull requests as wel

**Comment by vlapo** [comment]
Sure check issues or milestones and create PRs :)

**Comment by l2ubin** [comment]
sure. On it

**Pull request merged**
