### PR TITLE
fix: Add ignore parameter (taken from validatorjs) towards IsAlpha and IsAlphanumeric

### LINKED ISSUE #1144: question: isAlpha enhancement from validatorjs
I was trying to use `isAlphanumeric` validator, wondering if there was an option to allow one extra character while doing so (a space or `-` for example). Looks like it has been implemented in validatorjs [PR1286 - isAlpha enhancement ](https://github.com/validatorjs/validator.js/pull/1286) but I don't find it in class-validator...

**The problem:**
Usage in validatorjs : `.isAlpha('en-US', {ignore: ' '})`
Usage in class-validator : `.isAlpha('en-US', { ??? })`
image

Is it something not yet implemented, or is it normal ?

### PR DESCRIPTION
**Pull request by ImranSasudin**
## Description
Add `ignore` parameter into IsAlpha and IsAlphanumeric to utilize this parameter since it has already been implemented by validatorjs

## Checklist

- [x] the pull request title describes what this PR does (not a vague title like `Update index.md`)
- [x] the pull request targets the *default* branch of the repository (`develop`)
- [x] the code follows the established code style of the repository
  - `npm run prettier:check` passes
  - `npm run lint:check` passes
- [x] tests are added for the changes I made (if any source code was modified)
- [x] documentation added or updated
- [x] I have run the project locally and verified that there are no errors

### Fixes

fixes #[issue number], fixes #[issue number]

### CODE REVIEW

**Comment by ImranSasudin** [comment]
It's for this issue [#1144](https://github.com/typestack/class-validator/issues/1144)

**Comment by abelland** [comment]
any updates on this?

**Comment by ImranSasudin** [comment]
> any updates on this?

no update on my side. waiting for review.

**Comment by NoNameProvided** [comment]
If you are still interested in this change, please re-create the PR on the latest develop branch.

**Comment by NoNameProvided** [comment]
This is now tracked in https://github.com/typestack/class-validator/issues/1842.

**Pull request closed without merging**
