### PR TITLE
fix invalid nested

### PR DESCRIPTION
**Pull request by sh3d2**
hi,

my attempt to fix #137

### CODE REVIEW

**Comment by sh3d2** [comment]
@pleerock @NoNameProvided could you please have a look?

**Comment by szymonskirgajllo** [comment]
@pleerock @NoNameProvided what with this pr? can you merge it and release new version?

**Comment by NoNameProvided** [comment]
Hi! 

I am working my way through the issues, I haven't arrived to this PR yet.

**Comment by sh3d2** [comment]
hi @NoNameProvided is there anyone else that could have a look?

**Comment by NoNameProvided** [comment]
@sh3d2 thanks for the contrib! 🎉🎉🎉 (and sorry for the late merge)

**Pull request merged**
