### PR TITLE
feat(decorators): allow constraints of @ValidateIf to make reference …

### PR DESCRIPTION
**Pull request by hlibco**
…to the class hosting @ValidateNested

It adds a very necessary feature #278

### CODE REVIEW

**Comment by hlibco** [comment]
Hi @pleerock I'd appreciate if you can take a look at this very small PR that adds a feature to validate nested objects making reference to the parent object.

**Comment by galr52** [comment]
@hlibco any new updates?

**Comment by hlibco** [comment]
@galr52 At the moment I'm waiting for the revision from @NoNameProvided and @pleerock - It's a very small PR and we'll hopefully hear back from them soon.

**Comment by Genert** [comment]
Bump!

**Comment by Mautriz** [comment]
News on how to do this?

**Comment by AntonisFK** [comment]
any updates

**Comment by karer** [comment]
@pleerock @NoNameProvided please update it!

**Comment by vlapo** [comment]
https://github.com/typestack/class-validator/issues/278#issuecomment-604675151

**Comment by NoNameProvided** [comment]
Closing as wontfix. See linked discussion for details.

**Pull request closed without merging**
