### PR TITLE
feat: add `skipUndefinedProperties` and `skipNullProperties` options

### PR DESCRIPTION
**Pull request by ruscon**
PR for issue #308

previous dead pull request #353

### CODE REVIEW

**Comment by ruscon** [comment]
@vlapo can you merge this asap and make a new npm version ?

**Comment by henrikra** [comment]
Great 👍

**Comment by vlapo** [comment]
Thank you for contribution :)

**Comment by ruscon** [comment]
@vlapo new npm version ?

**Comment by vlapo** [comment]
I hope this weekend.

**Comment by ruscon** [comment]
@vlapo ping :/

**Comment by ruscon** [comment]
@vlapo Could you create at least a beta tag in the npm?

**Comment by vlapo** [comment]
`0.10.1` published. Please test :)

**Pull request merged**
