### PR TITLE
[UPDATE] bump repo version

### PR DESCRIPTION
**Pull request by uboat46**
## Description
Bump the repository version to fix validator type issues as seen on [this issue](https://github.com/typestack/class-validator/issues/2370)

## Checklist

- [x] the pull request title describes what this PR does (not a vague title like `Update index.md`)
- [x] the pull request targets the *default* branch of the repository (`develop`)
- [x] the code follows the established code style of the repository
  - `npm run prettier:check` passes
  - `npm run lint:check` passes
- [x] tests are added for the changes I made (if any source code was modified)
- [x] documentation added or updated
- [x] I have run the project locally and verified that there are no errors

### Fixes
fixes #[2370]

### CODE REVIEW

**Comment by sph3rex** [comment]
Might be a good addition, though not necessary in this PR to update the  .github/workflows/continuous-deployment-workflow.yml with something like:

```
// current content
- run: cp README.md build/README.md
- run: |
        jq 'del(.devDependencies) | del(.scripts)' package.json > build/package.json

        release_tag=$(echo "${GITHUB_REF}" | cut -d '/' -f 3)
        package_json=$(cat build/package.json)

        if [[ "${release_tag}" != "$(jq -r '.version' <<< "${package_json}")" ]]; then
          new_version="${release_tag}"
          jq '.version = "${new_version}"' build/package.json > updated_package.json
          mv updated_package.json build/package.json
        fi
- run: npm publish ./build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
 ```
 so that the pipeline bumps the version before trying to push if the package.json and tag name are different.

**Review by braaar — APPROVED** [review]

**Comment by braaar** [comment]
Apologies, I am not yet familiar with the setup in this repo for publishing releases. This was my mistake

**Comment by drealecs** [comment]
@braaar I think you need to recreate the tag `v0.14.1` tag with the new commit, 0a18ea2.
I guess you recreated, but using the previous commit, 0042559

**Comment by sph3rex** [comment]
> @braaar I think you need to recreate the tag `v0.14.1` tag with the new commit, [0a18ea2](https://github.com/typestack/class-validator/commit/0a18ea207c508fcc46f00efa44963f437606ec82). I guess you recreated, but using the previous commit, [0042559](https://github.com/typestack/class-validator/commit/0042559f45dcfd81d24bb0a46128ba3f32728fd5)

Is not that, there was no `npm i` ran so package-lock and package.json are out of sync. 0.14.0 in package-lock.json and 0.14.1 in package.json

**Comment by braaar** [comment]
@drealecs is right, I need to recreate the tag

**Pull request merged**
