### PR TITLE
feat: new `ValidatePromise` decorator - resolve promise before validate

### PR DESCRIPTION
**Pull request by queses**
Added new `@ValidatePromise` decorator to mark property as Promise that should to be resolved before validation.

Tests for new decorator lays in `promise-validation.spec.ts`.

Example of use:
```ts
class MySubClass {
  @MinLength(5)
  name: string;
}

class MyClass {
    @ValidatePromise() @ValidateNested()
    mySubClass: Promise<MySubClass>;
}

const model = new MyClass();
const mySubClass = new MySubClass();
mySubClass.name = "my";
model.mySubClass = Promise.resolve(mySubClass);

const errors = await validator.validate(model)
errors.length.should.be.equal(1);

errors[1].target.should.be.equal(model);
errors[1].property.should.be.equal("mySubClass");
errors[1].value.should.be.equal(await model.mySubClass);
expect(errors[1].constraints).to.be.undefined;
```

### CODE REVIEW

**Comment by queses** [comment]
Node v12 CI tests failed while v10 tests passed. Looks like library internal error

**Comment by queses** [comment]
Also looks like I forgot to increase version in `package.json`.

**Comment by vlapo** [comment]
@queses could you please rebase? Tests should be fixed in latest commit.

**Comment by queses** [comment]
Yup, it's OK now

**Comment by vlapo** [comment]
Thank you! :)

**Pull request merged**
