### PR TITLE
feat: implement @IsISO4217 validator

### LINKED ISSUE #1549: feature: add `@IsISO4217` decorator to check currency codes
### Description

`validator.js` offers validation for currency codes against the ISO4217 standard. 

### Proposed solution

Implement the `@IsIso4217()` decorator.

### PR DESCRIPTION
**Pull request by bassochette**
## Description
Implement @IsISO4217 validator

## Checklist

- [x] the pull request title describes what this PR does (not a vague title like `Update index.md`)
- [x] the pull request targets the *default* branch of the repository (`develop`)
- [x] the code follows the established code style of the repository
  - `npm run prettier:check` passes
  - `npm run lint:check` passes
- [x] tests are added for the changes I made (if any source code was modified)
- [x] documentation added or updated
- [x] I have run the project locally and verified that there are no errors

### Fixes

references #1549

### CODE REVIEW

**Review by braaar — DISMISSED** [review]

**Review by LeoFalco — DISMISSED** [review]

**Comment by kachar** [comment]
Awesome PR, thanks for the implementation. I hope it will be accepted soon :rocket:

**Comment by adrianmxb** [comment]
Just to bump this again, I don't see anything blocking the PR as it basically just implements a decorator for new [validator.js](https://github.com/validatorjs/validator.js/) functionality.

Can we maybe get this released soonish? :) @NoNameProvided

**Review by kejlerj — DISMISSED** [review]

**Comment by braaar** [comment]
Hey, @bassochette, things are happening on `develop`, so if you could clean up the diff this PR is hopefully close to getting merged :)

**Comment by bassochette** [comment]
All fresh and cleaned

Good job @braaar making things move around here.

**Comment by bassochette** [comment]
@NoNameProvided rebased and fixed prettier errors

**Comment by bassochette** [comment]
@braaar I'll need another review since rebasing staled the previous reviews

**Review by braaar — APPROVED** [review]

**Review by NoNameProvided — CHANGES_REQUESTED** [review]
This looks great, almost ready to merge!

The only problem it seems you messed up the table in the README, not just formatting but the content is missing for some rows. Please remove that change and only add a single new line for the new decorator entry.

**Comment by NoNameProvided** [comment]
This PR is superset by https://github.com/typestack/class-validator/pull/1824.

(You did not check the box that allows me to push to your origin branch, so I could not edit your PR.)

**Pull request closed without merging**
