### PR TITLE
feat: add all option in isuuid validator

### PR DESCRIPTION
**Pull request by rubiin**
As validatorjs supports all option as well which was missing in class-validator. So adding this

### CODE REVIEW

**Comment by rubiin** [comment]
@vlapo

**Comment by rubiin** [comment]
@vlapo @NoNameProvided

**Comment by vlapo** [comment]
Thank you

**Comment by rubiin** [comment]
i hope i get to use this soon

**Comment by nhactung** [comment]
Hi team, I was wondering if the npm package published.
The option is still missing in version 0.11.0, hope you guys upload it soon!

**Comment by rubiin** [comment]
@nhactung the code has been merged, i think it will be published on next release

**Comment by rubiin** [comment]
@vlapo is this available?

**Comment by qstiegler** [comment]
@vlapo Can you please publish the next release? Already three months...

**Comment by vlapo** [comment]
Sorry boys. Do not have time to OS. I will release today or tomorrow.

**Pull request merged**
