### PR TITLE
docs: fix typos and reformat decorators table

### PR DESCRIPTION
**Pull request by carlocorradini**
## Description
Fixed some readme typo(s) and decorators table formatting

## Checklist
- [X] the pull request title describes what this PR does (not a vague title like `Update index.md`)
- [X] the pull request targets the *default* branch of the repository (`develop`)
- [X] the code follows the established code style of the repository
  - `npm run prettier:check` passes
  - `npm run lint:check` passes
- [X] documentation added or updated
- [X] I have run the project locally and verified that there are no errors

### CODE REVIEW

**Comment by NoNameProvided** [comment]
Hey, thanks for opening this but it won't get merged. Formatting the markdown table is disabled on purpose.

**Comment by carlocorradini** [comment]
Have you seen that date decorators are broken?

**Comment by carlocorradini** [comment]
Can I ask why table formatting is disabled? With prettier formatting the result is well aligned and easily understandable.

**Comment by NoNameProvided** [comment]
> Have you seen that date decorators are broken?

What do you mean?

**Comment by carlocorradini** [comment]
See the screenshot:


minDate and maxDate are broken

**Review by NoNameProvided — APPROVED** [review]

**Pull request merged**
