### PR TITLE
feat: add `@IsBase58` validator

### PR DESCRIPTION
**Pull request by Kinggodhoon**
### Description

Adds implementation for `@IsBase58` validator. It checks whether the given string is a valid Base58 encoded string or not.

## Checklist
- [x] the pull request title describes what this PR does (not a vague title like `Update index.md`)
- [x] the pull request targets the *default* branch of the repository (`develop`)
- [x] the code follows the established code style of the repository
  - `npm run prettier:check` passes
  - `npm run lint:check` passes
- [x] tests are added for the changes I made (if any source code was modified)
- [x] documentation added or updated
- [x] I have run the project locally and verified that there are no errors

references #1821

### CODE REVIEW

**Comment by braaar** [comment]
Nice PR! I've added this to my epic #1747

**Comment by NoNameProvided** [comment]
Please rebase for review.

**Comment by Kinggodhoon** [comment]
@NoNameProvided 

I did rebase.

I'm not sure if this is right because I'm a beginner in development.

It would be very helpful if you could let me know if there is a better way.

thank you

**Comment by Kinggodhoon** [comment]
@NoNameProvided 
I did rebase.

I'm not sure if this is right because I'm a beginner in development.

It would be very helpful if you could let me know if there is a better way.

thank you.

**Review by NoNameProvided — APPROVED** [review]

**Pull request merged**
