### PR TITLE
feat: implement @IsTimezone validator

### PR DESCRIPTION
**Pull request by chandrashekhar07**
## Description
- @IsTimezone validator implemented that checks whether the given string is a valid IANA timezone.

## Checklist

- [x] the pull request title describes what this PR does (not a vague title like `Update index.md`)
- [x] the pull request targets the *default* branch of the repository (`develop`)
- [x] The code follows the established code style of the repository
  - `npm run prettier:check` passes
  - `npm run lint:check` passes
- [x] tests are added for the changes I made (if any source code was modified)
- [x] documentation added or updated
- [x] I have run the project locally and verified that there are no errors

references https://github.com/typestack/class-validator/issues/1795

### CODE REVIEW

**Comment by niklilland** [comment]
This would be very helpful for my current application! Thank you @chandrashekhar07!!!

**Comment by chandrashekhar07** [comment]
> This would be very helpful for my current application! Thank you @chandrashekhar07!!!

Thanks😉

**Comment by braaar** [comment]
Could you try to clean up the diff now since changes have been made on `develop`?

**Comment by NoNameProvided** [comment]
Superset by https://github.com/typestack/class-validator/pull/1796.

**Pull request closed without merging**
