### PR TITLE
feat: add nullable option for IsNotEmptyObject rule.

### PR DESCRIPTION
**Pull request by ytetsuro**
_Note: PR description was moved to issue for easier discoverability by @NoNameProvided ._

references #678.

### CODE REVIEW

**Comment by NoNameProvided** [comment]
Hi @ytetsuro! 

This looks good, however the decorator signature should be `IsNotEmptyObject({ nullable: boolean })`. 

Can you rebase this to the current develop or create a new PR for this? (You will need to update the tests as we moved from Mocha to Jest.

**Comment by ytetsuro** [comment]
> This looks good, however the decorator signature should be IsNotEmptyObject({ nullable: boolean }).

> Can you rebase this to the current develop or create a new PR for this? (You will need to update the tests as we moved from Mocha to Jest.

OK.
Thanks, good solution response.

**Comment by ytetsuro** [comment]
@NoNameProvided 
fixed.

Please re-review.

**Comment by NoNameProvided** [comment]
Thanks! 

PS: In future please don't use `it.each` for tests as it tends to make things harder to read.

**Comment by ytetsuro** [comment]
Thanks merged.

@NoNameProvided

> PS: In future please don't use it.each for tests as it tends to make things harder to read.

Yes, sir.
But why?

**Comment by NoNameProvided** [comment]
In unit tests, I like to keep things as simple as possible, and the `it.each` format makes things harder to read.

**Pull request merged**
