### PR TITLE
fix: create instance of ValidationError for whitelist errors

### LINKED ISSUE #325: whitelistValidation does not throw an error of type ValidationError.
when using below line for class validation 
```ts
const validationErrors = await validate(obj , { whitelist: true , forbidNonWhitelisted: true });
```
the validationErrors  in the above line is of type **ValidationError[]** for all the other cases except for when it is throwing error whitelistValidation .
When the error is **whitelistValidation**  "proptery should not exist" it is of type **Object[]**.Could you please let me know if this is a bug , if so could you please update the same to be of type **ValidationError[]**

### PR DESCRIPTION
**Pull request by nolazybits**
Fix #325

### CODE REVIEW

**Comment by vlapo** [comment]
Thank you! :)

**Comment by nolazybits** [comment]
@vlapo can you publish to npm please?

**Comment by nolazybits** [comment]
Coming back @vlapo . Can we push that to npm please?

**Comment by vlapo** [comment]
Done. Happy testing https://www.npmjs.com/package/class-validator/v/0.11.0

**Comment by nolazybits** [comment]
Thanks :)

**Pull request merged**
